### ISSUE TITLE
Add method to check error for specific field

### ISSUE THREAD

**Issue by aryanjaya** [laravel/jetstream-js#10]
Hi, thanks for making this library.

Currently, I try to use this library to display error message on vuetify text field component like this.

```
<v-text-field
  label="Name"
  v-model="form.name"
  :error="hasError('name')"
  :error-messages="form.error('name')"
  required
></v-text-field>
```

But I have to make a `hasError` method in every form component I make. I thought it would be better if this method was added to the `form` object.

So, instead of making it like this:
```
<v-text-field
  label="Name"
  v-model="form.name"
  :error="hasError('name')"
  :error-messages="form.error('name')"
  required
></v-text-field>
```
It would be better to make it like this:
```
<v-text-field
  label="Name"
  v-model="form.name"
  :error="form.hasError('name')"
  :error-messages="form.error('name')"
  required
></v-text-field>
```

Other suggestions are welcome.

**Comment by driesvints** [comment]
If you want to change anything feel free to attempt a PR 👍
