### ISSUE TITLE
Usage with Vue 3

### ISSUE THREAD

**Issue by m1guelpf** [laravel/jetstream-js#11]
When using the new Vue 3 composition API, the `setup` function [doesn't have access to `this`](https://v3.vuejs.org/guide/composition-api-setup.html#usage-of-this), which makes it impossible to use the form helpers.

To work around this, a `useForm` hook could be introduced that creates a new `InertiaForm` object when called.

**Comment by taylorotwell** [comment]
I know nothing about Vue 3 so any Vue 3 stuff is probably going to have to be a pull request for now.

**Comment by m1guelpf** [comment]
We can get access to the page props with Inertia's `usePage()` hook (which may introduce a dependency on the `@inertia/inertia-vue3` package? but I have no idea how to get the current Inertia instance.

```js
export function useForm(data, options) {
    const { props } = usePage()

    return InertiaForm.create()
            .withData(data)
            .withOptions(options)
            .withInertia(inertia) // <-- how can we get this
            .withPage(props),
}
``
