### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by alexis-riot** [laravel/jetstream-js#16]
- Jetstream Version: 1.2.0
- Jetstream JS Version: 1.2.0
- Laravel Version: 8.0

### Description:
There is a compatiblity problem with the latest version of InertiaJS. I'm using these versions:

```
        "@inertiajs/inertia": "^0.6.2",
        "@inertiajs/inertia-vue": "^0.4.2",
        "laravel-jetstream": "^1.2.0",
```
And I got this error on each form:
![image](https://user-images.githubusercontent.com/42867550/99287744-ed564400-283a-11eb-96b1-f92fea006db5.png)

The stack trace is on the `hasErrors`
```js
{
        key: 'hasErrors',
        value: function hasErrors() {
            return this.inertiaPage().errorBags[this.__options.bag] && Object.keys(this.inertiaPage().errorBags[this.__options.bag]).length > 0;
        }
```

And there is my form:
```js
<script>
    import Login from '../layout/Login';

    export default {
        name: "admin-login",
        layout: Login,
        data() {
            return {
                loginForm: this.$inertia.form({
                    email: '',
                    password: '',
                }, {
                    bag: 'default',
                }),
            };
        },
        methods: {
            login() {
                this.loginForm.post(route('admin.login'));
            },
        }
    };
</script>
```

**Comment by jroski** [comment]
I am experiencing the same issue, how did you solve it?

**Comment by driesvints** [comment]
1.x of laravel-jetstream is for the upcoming jetstream v2 release. Use ^0.2 for Jetstream v1.

**Comment by alexis-riot** [comment]
@jroski Have you update your packages recently ?

**Comment by jroski** [comment]
Yes, my packages are the following and I am still getting the error:
`
"@inertiajs/inertia": "^0.6.2",
"@inertiajs/inertia-vue": "^0.4.2",
"laravel-jetstream": "^0.2.1",
`

**Comment by alexis-riot** [comment]
Try to update `laravel-jetstream` to `^1.2.0`. I have no problem with these 3 versions.

**Comment by jroski** [comment]
My issue was that I do not have the composer Jetstream package installed (I was adding the laravel-jetstream npm package to get access to the `$inertia.form()` helper). The shared data was missing the `errorBags` property, resulting in this error.

Adding this snippet to the `share()` method of the middleware fixes the issue:
```
'errorBags' => function () {
				return collect(optional(Session::get('errors'))->getBags() ?: [])->mapWithKeys(function ($bag, $key) {
					return [$key => $bag->messages()];
				})->all();
			},
```

**Comment by driesvints** [comment]
> Try to update laravel-jetstream to ^1.2.0

@alexis-riot like I said: this version is for the next unreleased major version of Jetstream and shouldn't be used yet.
