### ISSUE TITLE
Cannot submit Inertia's form by a get method

### ISSUE THREAD

**Issue by nevmerzhitsky** [laravel/jetstream-js#3]
- Jetstream Version: 1.1.2
- Jetstream JS Version: 0.0.3
- Laravel Version: 8.0.1
- PHP Version: 7.4.10
- Database Driver & Version: -

### Description:

I'm creating search page for a site. Thus, I need a form which use GET-method.

I try to submit a form with "get" method. VueJS code looks like:

```html

<script>
import JetActionMessage from './../../Jetstream/ActionMessage'
import JetButton from './../../Jetstream/Button'
import JetFormSection from './../../Jetstream/FormSection'
import JetInput from './../../Jetstream/Input'
import JetInputError from './../../Jetstream/InputError'
import JetLabel from './../../Jetstream/Label'

export default {
    components: { /*...*/ },

    data() {
        return {
            form: this.$inertia.form({
                '_method': 'GET',
                query: '',
            }, {
                bag: 'search',
            }),
        }
    },

    methods: {
        searchCustomer() {
            this.form.submit('get', '/search/results', {})
        },
    },
}
</script>
```

But get JS error in a browser:

```
[Vue warn]: Error in v-on handler: "TypeError: this.__inertia[requestType] is not a function"

found in

---> <CreateSearchForm> at resources/js/Pages/Search/CreateSearchForm.vue
       <AppLayout> at resources/js/Layouts/AppLayout.vue
         <Index> at resources/js/Pages/Search/Index.vue
           <Inertia>
             <Root>
```

And this:

```
TypeError: this.__inertia[requestType] is not a function
    submit http://panel.checkout.test/assets/js/vendor.js:2006
    searchCustomer http://panel.checkout.test/assets/js/app.js:2500
    ...
```

I've checked code of the used InertiaJS library and see no `get` function at `node_modules/@inertiajs/inertia/src/inertia.js` (InertiaJS version 0.1.9 used, but for 0.1.7 is the same). There is `visit` function to doing this kind of requests. But `InertiaForm.__validateRequestType` doesn't accept this variant.

When I patched `InertiaForm.__validateRequestType` to check for `visit` instead of `get` and use it in `this.form.submit()` call, my task was done without any error and browser behaved fine.

### Steps To Reproduce:

I think the description contains them.

**Comment by driesvints** [comment]
This isn't supported I think. If you want to change anything here feel free to PR something. Thanks.
