### ISSUE TITLE
Can we make it run with latest version of Intertia.js

### ISSUE THREAD

**Issue by puncoz** [laravel/jetstream-js#7]
- Jetstream Version: v1.4.0
- Jetstream JS Version: 0.2.1
- Laravel Version: v8.9.0
- PHP Version: 7.4.11

### Description:
As a newer version of inertia.js has a breaking change that `$page` will no longer have all props instead it is an object with `props` as a property along with some other, can we update this jetstream-js package to support that? 

### Steps To Reproduce:
Here's the error I am getting while implementing the form.

![image](https://user-images.githubusercontent.com/7767424/95671262-6fa47600-0bb4-11eb-8415-22664b105fcb.png)

And this error is due to this line

![image](https://user-images.githubusercontent.com/7767424/95671269-92cf2580-0bb4-11eb-8591-fab5f54cbb1b.png)

because `inertiaPage` no longer have `errorBags` but a `props` property.

### Fixes:

We can simply fix this issue (at least or now) by updating the `src/InertiaForm.js` file as follows:

```
.withPage(() => app.prototype.$page);

// change above code to:

.withPage(() => app.prototype.$page.hasOwnProperty("props") ? app.prototype.$page.props : app.prototype.$page);
```

Similarly for vue3

```
.withPage(() => app.config.globalProperties.$page),

// change above code to:

.withPage(() => app.config.globalProperties.$page.hasOwnProperty("props") ? app.config.globalProperties.$page.props : app.config.globalProperties.$page),
```

PS: Of course using `withPage` will be still confusing, we can update that as `withInertiaProps` or something similar.

**Comment by InToSSH** [comment]
I am having the same problem.
```
"@inertiajs/inertia": "^0.4.1",
"@inertiajs/inertia-vue": "^0.3.2",
"laravel-jetstream": "^0.2.1",
```
Your fix worked when I used laravel-jetstream v0.0.3 (just changed the `app` to `Vue`), now with 0.2.1 it still doesn't work.

I updated from the default versions that came with the current Laravel + Jetstream + InertiaJS app install to see if the `onSuccess` callback is fixed, because I couldn't get it to work on the old version.

![chrome_2020-10-13_18-07-42](https://user-images.githubusercontent.com/6452373/95887399-125d2000-0d80-11eb-8713-d9344a8803f5.png)


Here is stripped down component which causes the issues:

```
<template>
    <v-card>
        <v-card-text>
            <v-simple-table >
                <template #default>
                    <tbody>
                    <tr v-for="(person, index) in form.persons" :key="index">
                        <td>
                            <v-text-field
                                class="mt-4"
                                outlined
                                dense
                                v-model="person.name"
                                label="Jméno a příjmení"
                                :error-messages="form.error(`persons.${index}.name`)"


                            ></v-text-field>
							 <v-text-field
								v-model="form.email"
								label="Email pro zasílání novinek"
								:error-messages="form.error('email')"
							></v-text-field>
                        </td>
                        
                    </tr>
                    </tbody>
                </template>
            </v-simple-table>         
        </v-card-text>
    </v-card>
</template>

<script>
export default {

    props: ['guests', 'current'],

    data() {
        return {
            form: this.$inertia.form({
                persons: [
                    {
                        name: '',
                    }
                ],
                email: '',
            }, {
                resetOnSuccess: false
            })
        };
    },
    methods: {

        submitForm() {
			this.form.post(route('attendance.store', this.current.guest_group_id), {
				preserveScroll: true,
				onSuccess: page => {
					console.log('sending successful');
				}
			});
        }    
    },
    
}
</script>
```
Part that causes the issue is `:error-messages="form.error(`persons.${index}.name`)"` because it doesn't have default value. It used to work on the old version. 
But still even if I delete these, I get an error when trying to send the form:
```
app.js:6859 Uncaught (in promise) TypeError: Cannot read property 'default' of undefined
    at Proxy.hasErrors (app.js:6859)
    at then (app.js:6776)
```

**Comment by aarondfrancis** [comment]
Here's a way to hack around it for now.

In your `app.js`
```js
Vue.use(InertiaForm);

let original = Vue.prototype.$inertia.form;
Vue.prototype.$inertia.form = (data = {}, options = {}) => {
    return original(data, options)
        .withPage(() => Vue.prototype.$page.props);
}
```

**Comment by driesvints** [comment]
A new 1.0.0 update was released for this. Thanks.
